#!/usr/bin/env bash
# Graham S. Paul (1-install_nginx_web_server)
# Modernizepackage list and install Nginx with automatic "yes"
#

echo -e "Updating and installing Nginx.\n"
sudo apt-get update -y -qq && \
	 sudo apt-get install nginx -y

echo -e "\nSetting up some minor stuff.\n"

# Begin nginx
sudo service nginx start

# Grant access to nginx on firewall
sudo ufw allow 'Nginx HTTP'

# Grant ownership to website user files for easy editing
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

# Backup default index
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

# Develop fresh index
echo -e "Hello World!" | dd status=none of=/var/www/html/index.nginx-debian.html

# Restarting nginx
sudo service nginx restart

echo -e "\nCompleted. ✅\n"
