#!/bin/bash

# Graham S. Paul (4-TCP_and_UDP_ports) - Display listening ports and program names

# Runs check if running with sudo/root privileges
if [[ $EUID -ne 0 ]]; then
  echo "Please run the script as root or with sudo."
  exit 1
fi

# Achieve listening sockets
netstat_output=$(netstat -tlnp)

# Sort and format the output
formatted_output=$(echo "$netstat_output" | awk '$6 == "LISTEN" {print $1, $4, $7}' | sed 's/.*://')

# Pulls the header
echo "Active Internet connections (only servers)"
echo "Proto Recv-Q Send-Q Local Address           PID/Program name"

# Pulls the listening sockets
echo "$formatted_output"

# Print a separator
echo

# Pulls the header for UNIX domain sockets
echo "Active UNIX domain sockets (only servers)"
echo "Proto RefCnt Flags       Type       State         I-Node   PID/Program name    Path"

# Achieves listening UNIX domain sockets
unix_output=$(netstat -pln --unix | awk '$6 == "LISTEN" {print $1, $9}')

# Pulls the listening UNIX domain sockets
echo "$unix_output"
