#!/usr/bin/env bash
# Graham S. Paul (1-debugging_made_short) - Send sigup to nginx after config
sudo sed -i 's/sites-enabled/sites-available/g' "/etc/nginx/nginx.conf"
sudo kill -HUP "$(pgrep -f 'nginx: master')"
