#!/usr/bin/env bash
# Graham S. Paul (10-fizzbuzz) - Display FizzBuzz when the number is a multiple of 3 and 5, otherwise, display number

for ((i = 1; i <= 100; i++)); do
    if ((i % 3 == 0)) && ((i % 5 == 0)); then
        echo "FizzBuzz"
    elif ((i % 3 == 0)); then
        echo "Fizz"
    elif ((i % 5 == 0)); then
        echo "Buzz"
    else
        echo "$i"
    fi
done
